### ISSUE TITLE
Only trigger restart of service[network] if state/settings changed on RHEL and derivatives

### ISSUE THREAD

**Issue by ericachelis** [3ofcoins/chef-cookbook-hostname#39]
With each execution of the hostname recipe a restart of service[network] is triggered on RHEL derivative platforms. 
https://github.com/3ofcoins/chef-cookbook-hostname/blob/v0.3.0/recipes/default.rb#L84
```
    service 'network' do
      action :restart
    end
```

This causes a temporarily interruption that can impact active network connections.  It would be great if the network service is only restarted if the state of the machine has changed.

**Comment by mattkasa** [comment]
+1

**Comment by xamebax** [comment]
Thanks!
