### ISSUE TITLE
Supermarket doesn't have latest release

### ISSUE THREAD

**Issue by slashterix** [3ofcoins/chef-cookbook-hostname#42]
https://supermarket.chef.io/cookbooks/hostname only has 0.3.0
Can you update to 0.4.0 ?

**Comment by brauliobo** [comment]
+1

**Comment by mburns** [comment]
Agreed. As we work towards 0.5.0, we should have the latest tagged stable release ([v0.4.0](https://github.com/3ofcoins/chef-cookbook-hostname/releases/tag/v0.4.0)) on the Supermarket.

+CC @mpasternacki , @xamebax

**Comment by patcon** [comment]
+1

@mpasternacki, if you're busy, would you consider giving someone else contributor access on supermarket?

**Comment by gionn** [comment]
ping

**Comment by frank-m** [comment]
+1 This would be great

**Comment by petewilcock** [comment]
+1

**Comment by kschroeder31** [comment]
A year later. There is a pretty huge bug in 3.0 that was fixed with 4.0. Supermarket should have the latest release.

**Comment by sclarson** [comment]
Still a thing.

**Comment by mpasternacki** [comment]
Uploaded, apologies about that taking so long.
